// Bundles the dashboard and writes it into the SDK as strings, so every
// implementation serves the same files. --check fails if the copy is stale.
// --serve <port> rebuilds on every request, for the dev server.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url).pathname;
const out = new URL("../../sdk/src/generated/dashboard.ts", import.meta.url);

export async function bundle({ minify = true } = {}) {
  const result = await build({
    entryPoints: [`${root}src/main.tsx`],
    bundle: true,
    minify,
    format: "esm",
    target: "es2020",
    jsx: "automatic",
    jsxImportSource: "preact",
    outdir: "out",
    write: false,
    legalComments: "none",
    loader: { ".css": "css" },
  });
  const js = result.outputFiles.find((f) => f.path.endsWith(".js")).text;
  const css = result.outputFiles.find((f) => f.path.endsWith(".css")).text;
  return { js, css };
}

function render({ js, css }) {
  const hash = createHash("sha256").update(js).update(css).digest("hex").slice(0, 12);
  return `// Generated by packages/dashboard/scripts/build.mjs. Do not edit.
export const DASHBOARD_JS = ${JSON.stringify(js)};
export const DASHBOARD_CSS = ${JSON.stringify(css)};
export const DASHBOARD_HASH = ${JSON.stringify(hash)};
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const file = render(await bundle());
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(out, "utf8");
    } catch {}
    if (current !== file) {
      console.error("dashboard: packages/sdk/src/generated/dashboard.ts is stale. Run npm run build --workspace packages/dashboard");
      process.exit(1);
    }
    console.log("dashboard: up to date");
  } else {
    writeFileSync(out, file);
    console.log(`dashboard: ${Math.round(file.length / 1024)} KB written`);
  }
}
