// Bundles the dashboard and writes it into the SDK as strings, so every
// implementation serves the same files. --check fails if the copy is stale.
// --serve <port> rebuilds on every request, for the dev server.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { world } from "./world.mjs";

const root = new URL("..", import.meta.url).pathname;
const out = new URL("../../sdk/src/generated/dashboard.ts", import.meta.url);

export async function bundle({ minify = true } = {}) {
  const result = await build({
    entryPoints: [`${root}src/main.tsx`],
    bundle: true,
    minify,
    format: "esm",
    target: "es2020",
    jsx: "automatic",
    jsxImportSource: "preact",
    outdir: "out",
    write: false,
    legalComments: "none",
    loader: { ".css": "css" },
  });
  const js = result.outputFiles.find((f) => f.path.endsWith(".js")).text;
  const css = result.outputFiles.find((f) => f.path.endsWith(".css")).text;
  return { js, css };
}

/**
 * Every language but English, which is in the bundle. Fails when a file has
 * a key English lacks or lacks one English has, so no language can quietly
 * fall behind.
 */
export function locales() {
  const dir = `${root}src/locales/`;
  const english = Object.keys(JSON.parse(readFileSync(`${dir}en.json`, "utf8"))).sort();
  const out = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json") && f !== "en.json").sort()) {
    const code = file.slice(0, -5);
    const messages = JSON.parse(readFileSync(dir + file, "utf8"));
    const keys = Object.keys(messages).sort();
    const missing = english.filter((k) => !(k in messages));
    const extra = keys.filter((k) => !english.includes(k));
    if (missing.length || extra.length) {
      throw new Error(`dashboard: ${file} is out of step with en.json. Missing: ${missing.join(", ") || "none"}. Extra: ${extra.join(", ") || "none"}.`);
    }
    out[code] = JSON.stringify(messages);
  }
  return out;
}

function render({ js, css }) {
  const hash = createHash("sha256").update(js).update(css).digest("hex").slice(0, 12);
  const map = world();
  const mapHash = createHash("sha256").update(map).digest("hex").slice(0, 12);
  const langs = locales();
  const langHash = createHash("sha256").update(JSON.stringify(langs)).digest("hex").slice(0, 12);
  return `// Generated by packages/dashboard/scripts/build.mjs. Do not edit.
export const DASHBOARD_JS = ${JSON.stringify(js)};
export const DASHBOARD_CSS = ${JSON.stringify(css)};
export const DASHBOARD_HASH = ${JSON.stringify(hash)};
/** Country shapes for the map, fetched only when someone opens it. */
export const WORLD_JSON = ${JSON.stringify(map)};
export const WORLD_HASH = ${JSON.stringify(mapHash)};
/** Messages for each language but English, fetched when someone picks it. */
export const LOCALES: Record<string, string> = ${JSON.stringify(langs)};
export const LOCALES_HASH = ${JSON.stringify(langHash)};
/** English, which the bundle carries itself; the server needs it for email. */
export const ENGLISH = ${JSON.stringify(JSON.stringify(JSON.parse(readFileSync(new URL("../src/locales/en.json", import.meta.url), "utf8"))))};
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const file = render(await bundle());
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(out, "utf8");
    } catch {}
    if (current !== file) {
      console.error("dashboard: packages/sdk/src/generated/dashboard.ts is stale. Run npm run build --workspace packages/dashboard");
      process.exit(1);
    }
    console.log("dashboard: up to date");
  } else {
    writeFileSync(out, file);
    console.log(`dashboard: ${Math.round(file.length / 1024)} KB written`);
  }
}
