// Builds the tracker and writes it into the SDK as a string, so every
// implementation serves the same bytes. --check fails if the copy is stale
// or the script has grown past its budget.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";

const BUDGET = 2048;
const out = new URL("../../sdk/src/generated/tracker.ts", import.meta.url);

const result = await build({
  entryPoints: [new URL("../src/tracker.js", import.meta.url).pathname],
  bundle: false,
  minify: true,
  target: "es2017",
  write: false,
  legalComments: "none",
});
const code = result.outputFiles[0].text.trim();
// The picker loads only on the owner's own visit, from the dashboard, so it has no budget.
const picked = await build({
  entryPoints: [new URL("../src/pick.js", import.meta.url).pathname],
  bundle: false,
  minify: true,
  target: "es2017",
  write: false,
  legalComments: "none",
});
const picker = picked.outputFiles[0].text.trim();
const gzipped = gzipSync(code).length;
const hash = createHash("sha256").update(code).digest("hex").slice(0, 12);

const file = `// Generated by packages/tracker/scripts/build.mjs. Do not edit.
export const TRACKER = ${JSON.stringify(code)};
export const TRACKER_HASH = ${JSON.stringify(hash)};
export const PICKER = ${JSON.stringify(picker)};
`;

if (gzipped > BUDGET) {
  console.error(`tracker: ${gzipped} bytes gzipped, over the ${BUDGET} byte budget`);
  process.exit(1);
}

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== file) {
    console.error("tracker: packages/sdk/src/generated/tracker.ts is stale. Run npm run build --workspace packages/tracker");
    process.exit(1);
  }
  console.log(`tracker: up to date, ${gzipped} bytes gzipped`);
} else {
  writeFileSync(out, file);
  console.log(`tracker: ${code.length} bytes, ${gzipped} gzipped`);
}
